#!/bin/bash

COMMITS=$(git log --pretty=format:'%s' | egrep '\d+\.' | uniq | sort -n)
perl -0777 -i -pe 's/```.*```/```\n'"$COMMITS"'\n```/igs' README.md

git update-index --add $README
git add $README

exit 0