#!/bin/bash

echo
if [ -a .commit ] then
  rm .commit

  COMMITS=$(git log --pretty=format:'%s' | egrep '\d+\.' | uniq | sort -n)
  perl -0777 -i -pe 's/```.*```/```\n'"$COMMITS"'\n```/igs' README.md

  git add $README
  git commit --amend -C HEAD --no-verify
fi

exit 0