#!/bin/bash

README=README.md

COMMITS=$(git log --pretty=format:'%s' | egrep '\d+\.' | uniq | sort -n)
perl -0777 -i -pe 's/```.*```/```\n'"$COMMITS"'\n```/igs' $README

git add $README
git commit -m "Update $README"

exit 0
