#!/bin/bash

echo

COMMITS=$(git log --pretty=format:'%s' | egrep '\d+\.' | uniq | sort -n)
perl -0777 -i -pe 's/```.*```/```\n'"$COMMITS"'\n```/igs' README.md

git add $README
git commit --no-verify -m "Update $README"

exit 0
