package com.panibrat.bitManipulation.Find_the_Difference_389

/*
389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

 */

class Solution {
    fun findTheDifference(s: String, t: String): Char {
        val value = t.fold(0, { v, c -> v + c.toInt() })
        return s.fold(value, { v, c -> v - c.toInt() }).toChar()
    }
}